// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Platform.AiNewsDelivery.Infrastructure.Persistence;

#nullable disable

namespace Platform.AiNewsDelivery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    [Migration("20260501051855_AddModelAliases")]
    partial class AddModelAliases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Platform.AiNewsDelivery.Domain.Entities.ModelAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("canonical_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_id");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId")
                        .IsUnique();

                    b.ToTable("model_aliases", (string)null);
                });

            modelBuilder.Entity("Platform.AiNewsDelivery.Domain.Entities.ModelChange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("change_type");

                    b.Property<double?>("DeltaPercent")
                        .HasColumnType("REAL")
                        .HasColumnName("delta_percent");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("detected_at");

                    b.Property<bool>("Dispatched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("dispatched");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("FieldName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("field_name");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("model_id");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("old_value");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAt", "Dispatched")
                        .HasDatabaseName("ix_changes_detected_dispatched");

                    b.HasIndex("ModelId", "ChangeType")
                        .HasDatabaseName("ix_changes_model_type");

                    b.ToTable("model_changes", (string)null);
                });

            modelBuilder.Entity("Platform.AiNewsDelivery.Domain.Entities.ModelSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("collected_at");

                    b.Property<string>("DataHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_hash");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("metrics_json");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("model_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_data");

                    b.HasKey("Id");

                    b.HasIndex("ModelId", "CollectedAt")
                        .HasDatabaseName("ix_snapshots_model_collected_desc");

                    b.HasIndex("ModelId", "Provider", "CollectedAt")
                        .IsUnique()
                        .HasDatabaseName("ux_snapshots_model_provider_collected");

                    b.ToTable("model_snapshots", (string)null);
                });

            modelBuilder.Entity("Platform.AiNewsDelivery.Domain.Entities.WorkerRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ChangesDetected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("changes_detected");

                    b.Property<string>("ErrorsLog")
                        .HasColumnType("TEXT")
                        .HasColumnName("errors_log");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<int>("ModelsCollected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("models_collected");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("worker_runs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
