// Migrations geradas automaticamente pelo EF Core — suprime análise de código
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage(
    "Performance",
    "CA1861:Avoid constant arrays as arguments",
    Justification = "Auto-generated by EF Core migrations tooling",
    Scope = "namespaceanddescendants",
    Target = "~N:Platform.AiNewsDelivery.Infrastructure.Persistence.Migrations")]
